name: Deploy Laravel to DirectAdmin

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # 1. Setup PHP & Install Library Backend (Laravel)
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2' # Sesuaikan dengan versi Laravel 12
          tools: composer

      - name: Install Composer Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev

      # 2. Setup Node.js & Install Library Frontend (Vite/Tailwind)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Menggunakan Node 20 agar Vite tidak error
          cache: 'npm'

      - name: Install NPM & Build
        run: |
          npm install
          npm run build

# 3. Upload ke Hosting via FTP
      - name: Deploy via FTP to HostData
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /
          dangerous-clean-slate: false
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/vendor/**
            .env.example
            README.md
            tests/**